project_name: shed

before:
  hooks:
    - go mod tidy
    - make completions

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/getshiphub/shed/cmd.version={{.Version}}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
      - completions/*

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: getshiphub
    name: shed

# TODO(@cszatmary): Figure out homebrew release
# brews:
#   - tap:
#       owner: getshiphub
#       name: homebrew-tap
#     commit_author:
#       name: cszatmary
#       email: cs@christopherszatmary.com
#     folder: Formula
#     description: "Easily manage Go tool dependencies"
#     test: |
#       system "#{bin}/shed --version"
#     install: |
#       bin.install "shed"
#       bash_completion.install "completions/shed.bash"
#       zsh_completion.install "completions/_shed"
