version: 2.1

gomod_cache_key: &gomod_cache_key shed-deps-20201218-{{ checksum "go.sum" }}
shed_cache_key: &shed_cache_key shed-tools-20201218-{{ checksum "shed.lock" }}

jobs:
  lint-build-test:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - restore_cache:
          name: Restore dependency cache
          keys:
            - *gomod_cache_key
      - restore_cache:
          name: Restore tool dependency cache
          keys:
            - *shed_cache_key
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          name: Cache dependencies
          key: *gomod_cache_key
          paths:
            - ~/go/pkg
      - save_cache:
          name: Cache tool dependencies
          key: *shed_cache_key
          paths:
            - ~/.cache/shed
      - run:
          name: Check files are formatted
          command: make check-fmt
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Build shed
          command: make build-snapshot
      - run:
          name: Run tests
          command: make test-ci

workflows:
  lint-build-test:
    jobs:
      - lint-build-test
